apiVersion: v1
kind: Service
metadata:
    name: jenkins_service
spec:
    type: NodePort
    selector:
        app: jenkins
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 32000
